import os
import smtplib
from email.message import EmailMessage
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

router = APIRouter(prefix="/api/v1/email", tags=["Email"])

class EmailRequest(BaseModel):
    cnic: str
    citizen_name: str
    organization: str
    recipient: str = "fidaimohsin04@gmail.com"
    sender: str = "fidaimohsin@gmail.com"

@router.post("/request-info")
async def send_info_request_email(req: EmailRequest):
    password = os.getenv("GMAIL_APP_PASSWORD")
    
    # Strip quotes if the user left them in the .env file
    if password:
        password = password.strip('"').strip("'")
        
    if not password or password == "paste_your_16_letter_app_password_here":
        raise HTTPException(
            status_code=500, 
            detail="GMAIL_APP_PASSWORD environment variable is not configured in .env file. Cannot send real email."
        )
        
    try:
        # Construct the email
        msg = EmailMessage()
        msg['Subject'] = f"URGENT: Information Request for CNIC {req.cnic}"
        msg['From'] = req.sender
        msg['To'] = req.recipient
        
        body = f"""Dear {req.organization} Support,

Please find attached the formal information request regarding the citizen with CNIC: {req.cnic}.
This request was automatically generated by the Federal Tax Intelligence Platform.

Regards,
Tax Intelligence System"""
        msg.set_content(body)
        
        # Generate a real valid PDF with FTI Logo and Formal Text
        from fpdf import FPDF
        import tempfile
        
        class PDF(FPDF):
            def header(self):
                # Logo
                logo_path = os.path.join(os.getcwd(), "backend", "assets", "fti_logo.png")
                if os.path.exists(logo_path):
                    self.image(logo_path, 10, 8, 50)
                self.set_font('Arial', 'B', 15)
                # Move to the right
                self.cell(80)
                # Title
                self.cell(30, 10, 'Federal Tax Intelligence', 0, 0, 'C')
                # Line break
                self.ln(30)
                
        pdf = PDF()
        pdf.add_page()
        
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, txt=f"Request for Information and Verification Regarding {req.cnic}", ln=True)
        pdf.ln(5)
        
        pdf.set_font("Arial", '', 11)
        pdf.cell(0, 10, txt="Dear Sir/Madam,", ln=True)
        pdf.ln(2)
        
        p1 = "I am writing on behalf of TaxIntel, an initiative focused on improving tax transparency and supporting the identification of potential discrepancies in publicly available financial and ownership information."
        pdf.multi_cell(0, 6, txt=p1)
        pdf.ln(4)
        
        p2 = f"During our review of available records, we identified certain information associated with {req.citizen_name}, CNIC/NTN/Registration No. {req.cnic}, that may require further verification."
        pdf.multi_cell(0, 6, txt=p2)
        pdf.ln(4)
        
        p3 = "We would appreciate it if your organization could provide, where legally permissible and in accordance with your applicable policies, any relevant information or clarification regarding the following:"
        pdf.multi_cell(0, 6, txt=p3)
        pdf.ln(2)
        
        # Bullet points
        bullets = [
            "Confirmation of the individual/entity's association with your organization",
            "Relevant registration, ownership, directorship, employment, or business information",
            "Any publicly disclosable records relating to the individual/entity",
            "Clarification regarding potential asset or tax discrepancies requiring verification",
            "Any other information that may assist in accurately verifying the records under review"
        ]
        for bullet in bullets:
            pdf.set_x(15) # indent 5 units from default 10 margin
            pdf.multi_cell(0, 6, txt=f"- {bullet}")
            
        pdf.ln(4)
        p4 = "This request is being made strictly for information verification and analytical purposes. We are not making any allegation of wrongdoing, and any information received will be treated responsibly and used only for lawful purposes."
        pdf.multi_cell(0, 6, txt=p4)
        pdf.ln(4)
        
        p5 = "If your organization requires a formal request, authorization, reference number, or additional documentation before releasing information, please let us know and we will provide the necessary details."
        pdf.multi_cell(0, 6, txt=p5)
        pdf.ln(4)
        
        p6 = "We would appreciate your assistance in helping us ensure that the information under review is accurate and properly verified.\n\nThank you for your time and cooperation."
        pdf.multi_cell(0, 6, txt=p6)
        pdf.ln(8)
        
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(0, 5, txt="Kind regards,", ln=True)
        pdf.cell(0, 5, txt="TaxIntel", ln=True)
        pdf.cell(0, 5, txt="Federal Tax Intelligence Team", ln=True)
        pdf.set_font("Arial", '', 11)
        pdf.cell(0, 5, txt="fidaimohsin@gmail.com", ln=True)
        
        # Save to temp file and read bytes
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            pdf.output(tmp.name)
            tmp.flush()
            
        with open(tmp.name, "rb") as f:
            pdf_bytes = f.read()
            
        os.unlink(tmp.name)
        
        msg.add_attachment(
            pdf_bytes, 
            maintype='application', 
            subtype='pdf', 
            filename=f"Info_Request_{req.cnic}.pdf"
        )
        
        # Connect to Gmail SMTP server and send
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login(req.sender, password)
        server.send_message(msg)
        server.quit()
        
        return {
            "success": True, 
            "message": f"Successfully sent PDF request to {req.organization} via {req.recipient}",
            "details": {
                "organization": req.organization,
                "cnic": req.cnic,
                "mode": "live"
            }
        }
    except smtplib.SMTPAuthenticationError:
        raise HTTPException(status_code=401, detail="Invalid Gmail App Password. Authentication failed.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to send email: {str(e)}")
